import type { Metadata } from "next";
import {Inter, Roboto} from "next/font/google"
import localFont from "next/font/local";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  
});
const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-roboto",
});

const nunitoLocal = localFont({
  src: "./fonts/Nunito.ttf",
  variable: "--font-nunito",
});
const generalSansLocal = localFont({
  src: "./fonts/GeneralSans.otf",
  variable: "--font-generalsans",
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* ${inter.className} ${roboto.className} ${nunitoLocal.className}   */}
      {/* <body className={`antialiased `}>{children}</body> */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${generalSansLocal.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
